config/routes.rb
Rails.application.routes.draw do
  resources :deposits_products

  resources :products

  resources :stores

  resources :deposits

  resources :categories

  resources :posts

  get 'deposits/:id/products' => 'deposits#products', as: :depositproducts

end

app/models/deposits_product.rb
class DepositsProduct < ActiveRecord::Base

	belongs_to :deposit
	belongs_to :product
end

app/controllers/deposits_products_controller.rb
class DepositsProductsController < ApplicationController
  before_action :set_deposits_product, only: [:show, :edit, :update, :destroy]

  # GET /deposits_products
  # GET /deposits_products.json
  def index
    @deposits_products = DepositsProduct.all
  end

  # GET /deposits_products/1
  # GET /deposits_products/1.json
  def show
  end

  # GET /deposits_products/new
  def new
    @deposits_product = DepositsProduct.new
  end

  # GET /deposits_products/1/edit
  def edit
  end

  # POST /deposits_products
  # POST /deposits_products.json
  def create
    @deposits_product = DepositsProduct.new(deposits_product_params)

    respond_to do |format|
      if @deposits_product.save
        format.html { redirect_to @deposits_product, notice: 'Deposits product was successfully created.' }
        format.json { render :show, status: :created, location: @deposits_product }
      else
        format.html { render :new }
        format.json { render json: @deposits_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deposits_products/1
  # PATCH/PUT /deposits_products/1.json
  def update
    respond_to do |format|
      if @deposits_product.update(deposits_product_params)
        format.html { redirect_to @deposits_product, notice: 'Deposits product was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposits_product }
      else
        format.html { render :edit }
        format.json { render json: @deposits_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits_products/1
  # DELETE /deposits_products/1.json
  def destroy
    @deposits_product.destroy
    respond_to do |format|
      format.html { redirect_to deposits_products_url, notice: 'Deposits product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposits_product
      @deposits_product = DepositsProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposits_product_params
      params.require(:deposits_product).permit(:cantidad,:deposit_id,:product_id,:precio)
    end
end

app/helpers/deposits_products_helper.rb
module DepositsProductsHelper
end

app/views/deposits_products/_form.html.erb
<%= form_for(@deposits_product) do |f| %>
  <% if @deposits_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposits_product.errors.count, "error") %> prohibited this deposits_product from being saved:</h2>

      <ul>
      <% @deposits_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deposit_id, "Deposito" %>*<br>
    <%= f.select :deposit_id, options_for_select(Deposit.all.pluck(:nombre,:id))%>
  </div>
  <div class="field">
    <%= f.label :product_id, "Producto" %>*<br>
    <%= f.select :product_id, options_for_select(Product.all.pluck(:nombre,:id))%>
  </div>

  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
    <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposits_products/edit.html.erb
<h1>Editing deposits_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposits_product %> |
<%= link_to 'Back', deposits_products_path %>

app/views/deposits_products/index.html.erb
<h1>Listing deposits_products</h1>

<table>
  <thead>
    <tr>
      <th>Deposito</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits_products.each do |deposits_product| %>
      <tr>
        <td><%= deposits_product.deposit.nombre %></td>
        <td><%= deposits_product.product.nombre %></td>
        <td><%= deposits_product.cantidad %></td>
         <td><%= deposits_product.precio %></td>
        <td><%= link_to 'Show', deposits_product %></td>
        <td><%= link_to 'Edit', edit_deposits_product_path(deposits_product) %></td>
        <td><%= link_to 'Destroy', deposits_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposits product', new_deposits_product_path %>

app/views/deposits_products/new.html.erb
<h1>New deposits_product</h1>

<%= render 'form' %>

<%= link_to 'Back', deposits_products_path %>

app/views/deposits_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @deposits_product.cantidad %>
</p>

<%= link_to 'Edit', edit_deposits_product_path(@deposits_product) %> |
<%= link_to 'Back', deposits_products_path %>